src/xbot/common/wpi_extensions/mechanism_wrappers/EncoderWPIAdapter.java
src/xbot/common/wpi_extensions/mechanism_wrappers/SolenoidWPIAdapter.java
src/xbot/common/wpi_extensions/mechanism_wrappers/SpeedControllerWPIAdapter.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XAnalogInput.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XBaseIO.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XDigitalInput.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XDigitalOutput.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XServo.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XSolenoid.java
src/xbot/common/wpi_extensions/mechanism_wrappers/XSpeedController.java
tests/edu/wpi/first/wpilibj/MockDigitalInput.java
tests/edu/wpi/first/wpilibj/MockServo.java
tests/edu/wpi/first/wpilibj/MockSolenoid.java
tests/edu/wpi/first/wpilibj/MockSpeedController.java

Add getChannel to all WPI mechanism wrappers

---

README.md

In preparation for the eventual promotion of this library wherever we decide to do it, this should add some useful content for prospective users. To look at the formatted version, you can open the branch page itself.
@aschokking @JohnGilb

Add new readme content for (future) people interested in the project

---

src/xbot/common/controls/actuators/wpi_adapters/ServoWPIAdapter.java
src/xbot/common/controls/actuators/wpi_adapters/SolenoidWPIAdapter.java
src/xbot/common/controls/sensors/wpi_adapters/PowerDistributionPanelWPIAdapter.java
src/xbot/common/injection/wpi_factories/RealWPIFactory.java

* Add missing Servo class
* Make sure everything ends up on the live window for test mode
@WasabiFan @JohnGilb @shahronak

Update wpi factory

---

src/xbot/common/math/PIDManager.java
tests/xbot/common/math/PIDManagerTest.java

Add output limits to pid manager

---

src/xbot/common/properties/XPropertyManager.java

Also cleaned up some pointless comments in the file.
@aschokking @JohnGilb

Use real value types instead of references in property manager

---

src/xbot/common/command/BaseRobot.java

Base autonomous command running

---

src/xbot/common/math/PID.java
src/xbot/common/math/PIDManager.java
src/xbot/common/math/PIDPropertyManager.java
tests/xbot/common/math/PIDManagerTest.java

-created override for isOnTarget that also accepts a derivative term

-If isOnTarget is called before calculate, it will always return FALSE

---

src/xbot/common/math/PID.java
src/xbot/common/math/PIDManager.java
src/xbot/common/math/PIDPropertyManager.java
tests/xbot/common/math/PIDManagerTest.java

-Added assertion check (for tests) that we're not using negative tolerances
-Split enable/disable and tolerance values into separate properties
-Added tests for these behaviors

Improvements to PIDManager re: Feedback

---

commonlib-build.xml
tests/xbot/common/logging/SafeRobotAssertionTest.java
tests/xbot/common/math/PIDManagerTest.java
tests/xbot/common/subsystems/PoseSubsystemTest.java

-Renamed one *Tests class to *Test.
-Noticed some checkstyle warnings for PIDManagerTest, cleaned up a bit
-Used a better import

-Travis should only run classes that end in Test.

---

src/xbot/common/controls/sensors/XboxControllerWpiAdapter.java

Sticks on Gamepad were not correctly configured.

Changed the buttons as they were not properly configured

---

checkstyle_suppressions.xml

Dep https://github.com/Team488/TeamXbot2017/pull/59

Suppress JSON libraries

---

src/xbot/common/command/BaseCommand.java
src/xbot/common/controls/sensors/MockXboxController.java

Created a basic end logging for all commands

Feature/implement end logging 

---

src/xbot/common/subsystems/BaseDriveSubsystem.java

*Use LoggingLatch to check if XCanTalons are null
*Add stop method to the DriveBaseSubystem

Logging more in DriveBaseSubsystem

---

src/xbot/common/logic/Latch.java
tests/xbot/common/logic/LatchTest.java

Added Latch Tests
We didn't save the previous value so saveValueAndAlertWatchers was only being called once.

Fix Latch logic

---

src/main/java/xbot/common/controls/actuators/XCANTalon.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonWPIAdapter.java

So it can be used in the LiveWindow.

Feature/make XCANTalon extend SendableBase

---

src/main/java/xbot/common/controls/actuators/XCANTalon.java
src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java

DriveSubsystem should start tracking XCANTalon telemetry.

XCANTalons should track position/velocity as properties.

---

.travis.yml
build.gradle
src/main/java/edu/wpi/first/wpilibj/MockLidarLite.java
src/main/java/edu/wpi/first/wpilibj/MockRobotState.java
src/main/java/edu/wpi/first/wpilibj/MockXboxControllerAdapter.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/VictorAppearingAsTalonWPIAdapter.java
src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
src/test/java/xbot/common/logic/LatchTest.java
src/test/java/xbot/common/math/FieldPointTest.java
src/test/java/xbot/common/subsystems/drive/HeadingAssistModuleTest.java
xbotcheckstyle.xml

In doing this I upgraded our checkstyle config file to handle breaking changes in checkstyle 8.0+. Also, I removed the check for sequences of capital letters in class names and added a check for "auto-generated" TODOs.

Add checkstyle to Gradle build and run it on Travis

---

src/main/java/xbot/common/controls/actuators/wpi_adapters/VictorAppearingAsTalonWPIAdapter.java
src/main/java/xbot/common/logging/RobotAssertionManager.java

At the moment, it'll have lots of funky behavior, such as followers running at full power all the time.
This hasn't been tested on-robot.

Fully support our usage of Talons in VictorAppearingAsTalonWpiAdapter

---

.travis.yml

<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% INITIALIZING [0s]> settings<-------------> 0% > loading<-------------> 0% > loading<-------------> 0% > loading<-------------> 0% CONFIGURING [1s]> root project<-------------> 0% CONFIGURING [1s]> root project<-------------> 0% CONFIGURING [1s]> root project<-------------> 0% CONFIGURING [1s]> root project<-------------> 0% CONFIGURING [1s]> root project > Resolve dependencies of detachedConfiguration1<-------------> 0% CONFIGURING [1s]> root project > …

Omit colors and progress bars when running Gradle on Travis

---

src/main/java/xbot/common/logic/WatchdogTimer.java
src/test/java/xbot/common/logic/WatchdogTimerTest.java

I'm using this in the offboard comms subsystem to monitor connection state, but I figure it could be useful in other places too. It's pretty much just a timeout-based latch.

Add watchdog timer class

---

src/main/java/xbot/common/command/BaseRobot.java
src/main/java/xbot/common/injection/RobotModule.java
src/main/java/xbot/common/injection/UnitTestModule.java
src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/MockDriveSubsystem.java
src/test/java/xbot/common/math/PlanarVisualizationPanel.java
src/test/java/xbot/common/math/PurePursuitTest.java
src/test/java/xbot/common/subsystems/drive/PurePursuitCommandTest.java

Remove warnings from test code

Remove unused imports

---

build.gradle
install_plugins.bat
install_plugins.sh

And remove old eclipse plugin stuff.

Include printing final test results

---

build.gradle
src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
src/main/java/xbot/common/networking/OffboardCommunicationClient.java
src/main/java/xbot/common/networking/ZeromqListener.java
src/test/java/xbot/common/injection/wpi_factories/TestCommonLibFactory.java
src/test/java/xbot/common/networking/ZeromqListenerTest.java
src/test/java/xbot/common/networking/ZeromqTestServer.java

Adds a simple Subscriber client into the SCL, as well as a demo Publisher client.

ZeroMQ Implementation

---

src/main/java/xbot/common/injection/RobotModule.java
src/main/java/xbot/common/subsystems/drive/PurePursuitCommand.java
src/test/java/xbot/common/subsystems/drive/PurePursuitCommandTest.java

CommonLibFactory did not have a binding for ZeroMQ
Perpindicular logic does not yet work for pure pursuit

Minor bugfixes

---

src/main/java/xbot/common/controls/sensors/ChordButton.java
src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
src/test/java/xbot/common/injection/wpi_factories/TestCommonLibFactory.java

For now, these will have to be carefully manually created. Eventually, we can move the creation into XJoystick, which can track how many of these can be created.

Adds Chorded Buttons

---

src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
src/test/java/xbot/common/injection/wpi_factories/TestCommonLibFactory.java

Make CommonLibFactory extend PIDFactory exposing all PIDFactory as part of the CommonLibFactory.

Expose PIDFactory methods on CommonLibFactory

---

src/main/java/xbot/common/properties/PropertyFactory.java
src/test/java/xbot/common/properties/PropertyFactoryTest.java

Ref https://app.asana.com/0/16170612236108/1114634427426144

Filter out double slashes from property names

---

src/main/java/xbot/common/command/BaseRobot.java
src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java

Copy in from 2018 robot project and make it the default way auto commands are selected

AutonomousCommandSelector

---

src/main/java/xbot/common/injection/SimulatorModule.java

So we can put commands on the smartdashboard

SimulationModule: Use real command putter

---

src/main/java/xbot/common/simulation/WebotsClient.java

WebotsClient side of https://github.com/Team488/Webots/pull/41

WebotsClient: drawLine()

---

src/main/java/xbot/common/simulation/ResetSimulatorPositionCommand.java
src/main/java/xbot/common/simulation/SimulationPayloadDistributor.java

Handle a little bit of async delay on the Webots side when resetting position

Handle a little bit of async delay on the Webots side

---

src/main/java/xbot/common/simulation/WebotsClient.java

SCL side of https://github.com/Team488/Webots/pull/42

drawLine(): Support setting color and z-index

---

src/main/java/xbot/common/simulation/WebotsClient.java

Depends on https://github.com/Team488/Webots/pull/44

Add drawArrow fn to WebotsClient

---

src/main/java/xbot/common/simulation/WebotsClient.java

Depends on https://github.com/Team488/Webots/pull/45

Add drawCircle() to WebotsClient

---

src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANTalon.java

Which matches what the mock internal encoder is doing.

MockCANTalon: setPosition: Change type to double

---

.vscode/settings.json

Based on https://www.chiefdelphi.com/t/unit-testing-java-io-ioexception-wpihaljni/372288/18, paths differ slightly

Update settings.json to fix test execution in VS Code UI

---

build.gradle

Apparently this will fix random joystick disconnects.

Update WPI lib

---

src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANSparkMax.java

…at we can offset the position reported from simulators

Feature/Support positional PID in MockCANSparkMax

---

src/main/java/xbot/common/math/PID.java
src/main/java/xbot/common/math/PIDFactory.java
src/main/java/xbot/common/math/PIDManager.java
src/main/java/xbot/common/math/PIDPropertyManager.java
src/test/java/xbot/common/math/PIDManagerTest.java

As we often just want i to apply a little bit near the goal

Add iZone param to PIDManager

---

src/main/java/xbot/common/command/BaseRobot.java

- Silence driver station joystick warning
- Silence many forms of loop overrun message

Suppress wpi loop overrun logs and joystick warnings

---

src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java

This will enable subclasses to override things more effectively

BasePoseSubsystem: private -> protected

---

src/main/java/xbot/common/command/BaseRobot.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java

Make some velocity properties public for easier testing (otherwise, mocking the entire mobility stack is pretty challenging)

Glacier Peak Day 1 - Small changes

---

src/main/java/xbot/common/logging/LoggingLatch.java
src/main/java/xbot/common/logic/Latch.java
src/main/java/xbot/common/logic/TimeStableValidator.java
src/test/java/xbot/common/logic/LatchTest.java

Note: renamed Latch `addObserver` to `setObserver` to better describe what's going on.

Document some of the logic functions

---

src/main/java/xbot/common/command/BaseRobot.java
src/main/java/xbot/common/injection/modules/SimulationModule.java
src/main/java/xbot/common/math/XYPairStruct.java
src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/SwerveSimpleTrajectoryCommand.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
src/main/java/xbot/common/trajectory/LowResField.java
src/main/java/xbot/common/trajectory/Obstacle.java
src/main/java/xbot/common/trajectory/SimpleTimeInterpolator.java
src/main/java/xbot/common/trajectory/SwerveSimpleTrajectoryLogic.java
src/main/java/xbot/common/trajectory/XbotSwervePoint.java
src/test/java/xbot/common/simulation/SimulateMockCANTalonTest.java
src/test/java/xbot/common/simulation/SimulatedIMUTest.java
src/test/java/xbot/common/simulation/SimulatedMockAbsoluteEncoderTest.java
src/test/java/xbot/common/simulation/SimulatedSolenoidTest.java
src/test/java/xbot/common/simulation/SimulatedTimerTest.java
src/test/java/xbot/common/simulation/SimulationPayloadDistributorTest.java
src/test/java/xbot/common/trajectory/LowResFieldTest.java
src/test/java/xbot/common/trajectory/ObstacleTest.java

Also, as part of getting a crummy on-laptop simulator working, I inadvertently broke objects that expect a MockTimer (mostly related to Webots). Suppressing those tests for now, since we can get more value out of local sim for the next few weeks.

Bring in updated Trajectory code from 2019 

---

.github/CODEOWNERS
.github/pull_request_template.md

Add CODEOWNERS and PR template

---

build.gradle
vendordeps/AdvantageKit.json

Update WPILib and AKIT

---

src/main/java/xbot/common/controls/sensors/XDigitalInput.java

Fix Digital Input bug

---

build.gradle
src/main/java/xbot/common/command/package-info.java

It's not always easy for new developers to understand how to use maintainers. Let's start to document it!
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206398294118271

Add some stub documentation for how to use maintainers.

---

src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java

Make "blue to red" coordinate conversion easier
Allow users to reflect Translation2d alongside Pose2d.

Add some overloads to make blue to red easier

---

src/main/java/xbot/common/command/BaseMaintainerCommand.java
src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveModuleSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/commands/SwerveDriveMaintainerCommand.java

Pipe in basic velocity control of drive wheels

---

src/main/java/xbot/common/math/MovingAverage.java
src/main/java/xbot/common/math/MovingAverageForDouble.java
src/main/java/xbot/common/math/MovingAverageForTranslation2d.java

Adds moving average for basic physics
A base class, and two specific classes for ease of use (Translation2d and Double)

Add moving average

---

build.gradle
src/main/java/org/photonvision/PhotonCameraExtended.java
src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
vendordeps/PathplannerLib.json

Installed PathPlanner for testing
Installed PathPlannerLib and made getSwerveModuleStates() public

Path planner

---

src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveModuleSubsystem.java

Enables a novice mode for new drivers to learn the robot
Pipes through a mode that lowers the max velocity and min/max outputs of the individual drive wheels.

NoviceMode

---

src/main/java/xbot/common/command/BaseMaintainerCommand.java

It can be hard to understand this maintainer / decision system.
Adding a _little_ bit more documentation and a state flow diagram

BaseMaintainerCommand doc

---

vendordeps/photonlib.json

new PhotonLib version

---

vendordeps/NavX.json

Update NavX lib to non-beta version

---

src/main/java/xbot/common/math/DoubleInterpolator.java
src/main/java/xbot/common/math/PID.java
src/main/java/xbot/common/math/PIDPropertyManager.java

- Fix bug in PID iZone calculation
- Promote iZone to important property
- Add generic DoubleInterpolator

Small changes to support 2024 Arm PID

---

src/main/java/xbot/common/controls/sensors/XXboxController.java
src/main/java/xbot/common/controls/sensors/buttons/AdvancedXboxAxisTrigger.java
src/test/java/xbot/common/controls/sensors/XboxControllerTest.java

I need more buttons on controllers!
Axis buttons can use negative and positive ranges.

support negative axis buttons

---

build.gradle
vendordeps/AdvantageKit.json

New WPILib has some important fixes for AprilTag locatiosn json file.
Update WPILib and AKit

Update WPILib to 2024.3.1

---

src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
vendordeps/PathplannerLib.json

update PathPlannerLib and create new method to make pathplanner autos work
updated PathPlannerLib and created getMaxTargetTurnRate()  method in BaseSwerveDriveSubsystem

Scl path planner

---

src/test/java/xbot/common/math/DoubleInterpolatorTest.java

Add test for double interpolator (porting Junyu's code)

---

vendordeps/photonlib.json

Use newer PV version

---

src/main/java/xbot/common/injection/electrical_contract/CameraInfo.java
src/main/java/xbot/common/injection/electrical_contract/XCameraElectricalContract.java

Part of migrating vision code to common-lib for easy reuse between seasons
Moving contract types to SCL

Add camera contract types to commonlib

---

src/main/java/xbot/common/injection/electrical_contract/CameraInfo.java
src/main/java/xbot/common/injection/electrical_contract/XCameraElectricalContract.java
src/main/java/xbot/common/subsystems/vision/AprilTagCamera.java
src/main/java/xbot/common/subsystems/vision/CameraCapabilities.java
src/main/java/xbot/common/subsystems/vision/SimpleCamera.java

SCL shouldn't have game specific code

[Vision] Re-genericise vision code and support multiple camera types

---

src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java

Set defaults based on robot testing

---

src/main/java/xbot/common/controls/actuators/XCANSparkMax.java

I was still seeing occasional "teleports" with Odometry. When I looked at the logs in AdvantageScope, i saw there were times we started getting bad data even before getting an error code. 
We also saw issues where a module would be aggressively resetting, which meant we also sent lots of messages to set up its status frames again and again.
Overall, I noticed three things that indicate bad data:
* Bus Voltage reports 0
* Position gets set to 0.244
* Error is present
* If we see any of the three suspicious cases above, "lose trust" in position until the value moves away from the strange position value.

Improve Odometry "bad data" rejection

---

src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANSparkMax.java

This was preventing proper data replay in simulation

Akittify mock spark max

---

src/main/java/xbot/common/advantage/AKitLogger.java
src/main/java/xbot/common/controls/actuators/XCANSparkMax.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/commands/SwerveSteeringMaintainerCommand.java

Reduce properties

---

src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java

Add dirty flag to indicate whether the autonomous is changed or not

---

src/main/java/xbot/common/subsystems/drive/SwerveSimpleTrajectoryCommand.java

This allows us to continuously rotate while moving somewhere. This was used in an autonomous program to "knock about" a bunch of Notes.

Support for continuous rotation in SwerveSimpleTrajectoryCommand

---

src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java

remove the dirty flag and use programname instead

---

src/main/java/xbot/common/math/PIDPropertyManager.java

Make f important

---

src/main/java/xbot/common/injection/electrical_contract/XSwerveDriveElectricalContract.java
src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/ISwerveAdvisorDriveSupport.java
src/main/java/xbot/common/subsystems/drive/swerve/ISwerveAdvisorPoseSupport.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveRotationAdvisor.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveModuleSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSuggestedRotation.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java

Because we will incorporate swerve onto the FRC template by default
Added stuff to the swerve folder inside drive
Did I put everything in the correct place?

FRCRobotTemplate SCL update

---

vendordeps/PathplannerLib.json

Old library version not longer supported
Update to new PathPlanner version.

Update to newer library

---

src/main/java/xbot/common/subsystems/vision/AprilTagVisionIO.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVision.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionSubsystem.java

We need more details about the nearest AprilTag target for positioning the robot
Log and emit more information about the targets.

Expose more details about the targeted apriltag for consumption

---

src/main/java/xbot/common/controls/actuators/XCANMotorController.java
src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/commands/ChangeActiveSwerveModuleCommand.java

- Motors can now be inverted
- Adds more consistent Unit behavior

Fixes for Swerve discovered with 2025 chassis

---

src/main/java/xbot/common/injection/modules/SimulationModule.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
src/main/java/xbot/common/subsystems/pose/MockBasePoseSubsystem.java

Vision sim: update how it gets ground truth

---

vendordeps/photonlib.json

updating photon lib to 2025.1.1
photonlib venderops

update photonlib to 2025.1.1

---

src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java

Remove unnecessary properties

---

src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
src/main/java/xbot/common/controls/sensors/XTimer.java

To help when simulating the robot
Also threw in a Unit-ified time call on XTimer

ability to set mock can motor controller velocity

---

build.gradle
src/main/java/xbot/common/controls/io_inputs/LaserCANInputs.java
src/main/java/xbot/common/controls/sensors/XLaserCAN.java
src/main/java/xbot/common/controls/sensors/mock_adapters/MockLaserCAN.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/LaserCANWpiAdapter.java
src/main/java/xbot/common/injection/components/BaseComponent.java
src/main/java/xbot/common/injection/modules/MockDevicesModule.java
src/main/java/xbot/common/injection/modules/RealDevicesModule.java
src/test/java/xbot/common/injection/factories/TestAllFactoryClasses.java
vendordeps/LaserCAN.json

Adds support for the LaserCAN device

Adds LaserCAN devices

---

src/main/java/xbot/common/controls/sensors/mock_adapters/MockLaserCAN.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java

Fix uninitialized values that can break logic

---

src/main/java/xbot/common/command/BaseSetpointCommand.java

Update isFinished method to return true for setpoint commands

---

azure-pipelines.yml
build.gradle
src/main/java/xbot/common/logging/RobotAssertionManager.java

Cache gradle artifacts

---

src/main/java/xbot/common/command/BaseRobot.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionCameraHelper.java

- Add minimum distances for using AprilTags for pose
- Support different loop periods for the main robot loop

More Vision rejection thresholds & Settable robot loop duration

---

src/main/java/xbot/common/controls/actuators/XCANMotorController.java
src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
src/main/java/xbot/common/controls/sensors/mock_adapters/MockCANCoder.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveModuleSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java

Clean up some of the top memory allocations running locally

---

src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java

Talons have been unpredictable on startup. Suspicion is that it may be due to the device not being ready yet at boot.
Wait up to 2 seconds in the constructor of the TalonFX for a status frame to be received, indicating that it is online. Tune some of the other logging so that it is less noisy and makes use of alerts.

Wait for TalonFX to be responsive on startup

---

src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java

Revert buggy changes to SwerveSteeringSubsystem

---

src/main/java/xbot/common/controls/actuators/XCANMotorController.java
src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/LaserCANWpiAdapter.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java

* Sets LaserCAN to useful configurations by default (make configurable later)
* Change defaults for SwerveDriveSubsystem PID

2025-02-17 SCL Bringup (v2)

---

azure-pipelines.yml

Further build pipeline optimizations

---

src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveModuleSubsystem.java
src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java

Changes to support more straightforward drive calibration

---

src/main/java/xbot/common/subsystems/drive/SwerveSimpleBezierCommand.java
src/main/java/xbot/common/trajectory/SimpleInterpolator.java
src/main/java/xbot/common/trajectory/SwerveSimpleBezierLogic.java

Allows for Curves without the robot skipping the curve (ChasePoint waits at the next point until a distance)
Copying 3 files modified one file
I did this so it wont bother anyone elses code :)
this does not clash with anything else, it is its own classes

Simple Interpolator

---

src/main/java/xbot/common/controls/io_inputs/XEncoderInputs.java
src/main/java/xbot/common/controls/sensors/XEncoder.java
src/main/java/xbot/common/controls/sensors/mock_adapters/MockEncoder.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/EncoderWPIAdapter.java
src/test/java/xbot/common/injection/factories/TestAllFactoryClasses.java
src/test/java/xbot/common/simulation/SimulationPayloadDistributorTest.java

Encoders are being used this year for follow wheels.

Support XEncoder in Akit

---

src/main/java/xbot/common/subsystems/drive/SwerveSimpleBezierCommand.java
src/main/java/xbot/common/trajectory/SwerveSimpleBezierLogic.java

change to use bezier (I forgot to set it, it was still using the old ghost logic my fault)

adding bezier curves (local)

---

src/main/java/xbot/common/controls/actuators/XCANMotorControllerFactoryImpl.java
src/main/java/xbot/common/controls/actuators/wpi_adapters/CANVictorSPXWpiAdapter.java
src/main/java/xbot/common/injection/electrical_contract/MotorControllerType.java
vendordeps/Phoenix5.json

Minimum set of support for VictorSPX

---

src/main/java/xbot/common/command/BaseRobot.java
src/main/java/xbot/common/command/XScheduler.java

Our robot startup test doesn't make it easy to see why it may have failed.
Track the latest init and startup exceptions so that we can report them from the test suite.

Report exception on init and in scheduler

---

src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java

Add hooks to configure audio on TalonFX

---

src/main/java/xbot/common/controls/io_inputs/XGyroIoInputs.java
src/main/java/xbot/common/controls/sensors/XGyro.java
src/main/java/xbot/common/controls/sensors/mock_adapters/MockGyro.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/InertialMeasurementUnitAdapter.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/Pigeon2Adapter.java
src/main/java/xbot/common/injection/electrical_contract/IMUInfo.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java

Add Acceleration from IMU

---

src/main/java/xbot/common/subsystems/vision/AprilTagVisionSubsystem.java

Helps other systems make decisions based on camera health.

Plumb isCameraConnected through the AprilTagVisionSubsystem

---

src/main/java/xbot/common/command/DelayViaSupplierCommand.java
src/main/java/xbot/common/command/SimpleWaitForMaintainerCommand.java
src/main/java/xbot/common/controls/actuators/XCANMotorController.java
src/main/java/xbot/common/controls/sensors/AnalogDistanceSensor.java
src/main/java/xbot/common/controls/sensors/SimulatedAnalogDistanceSensor.java
src/main/java/xbot/common/controls/sensors/XAnalogDistanceSensor.java
src/main/java/xbot/common/controls/sensors/XEncoder.java
src/main/java/xbot/common/logic/TimeStableValidator.java
src/main/java/xbot/common/math/MathUtils.java
src/main/java/xbot/common/math/PID.java
src/main/java/xbot/common/properties/DoubleProperty.java
src/main/java/xbot/common/subsystems/drive/SwerveSimpleBezierCommand.java
src/main/java/xbot/common/subsystems/drive/SwerveSimpleTrajectoryCommand.java
src/main/java/xbot/common/subsystems/pose/commands/SetRobotHeadingCommand.java
src/main/java/xbot/common/subsystems/vision/AprilTagCamera.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVisionSimulated.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionSubsystem.java
src/test/java/xbot/common/subsystems/vision/AprilTagVisionSubsystemTest.java

Migrate to variants of interfaces that avoid boxing

---

src/main/java/xbot/common/controls/io_inputs/XGyroIoInputs.java
src/main/java/xbot/common/controls/sensors/XGyro.java
src/main/java/xbot/common/controls/sensors/mock_adapters/MockGyro.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/InertialMeasurementUnitAdapter.java
src/main/java/xbot/common/controls/sensors/wpi_adapters/Pigeon2Adapter.java
src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
src/test/java/xbot/common/simulation/SimulatedIMUTest.java
src/test/java/xbot/common/subsystems/drive/HeadingAssistModuleTest.java
src/test/java/xbot/common/subsystems/drive/HeadingModuleTest.java
src/test/java/xbot/common/subsystems/pose/PoseSubsystemTest.java

Change Gyro to use Angle, AngularVelocity. Make Pigeon2 implementation more efficient.

XGyro to Measures system

---

src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java

Dynamic PID manager for method

---

src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVisionSimulated.java

Fix booboo in vision sim

---

src/main/java/xbot/common/injection/electrical_contract/CameraInfo.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionCameraHelper.java
src/main/java/xbot/common/subsystems/vision/AprilTagVisionSubsystem.java

Exclude back camera until heading issue figured out.

Exclude rear camera from pose
