- src/xbot/common/injection/RobotModule.java
- src/xbot/common/wpi_extensions/BaseCommand.java
- src/xbot/common/wpi_extensions/BaseCommandGroup.java
- src/xbot/common/wpi_extensions/RealSmartDashboardCommandPutter.java
- src/xbot/common/wpi_extensions/SmartDashboardCommandPutter.java
- tests/xbot/common/injection/UnitTestModule.java
- tests/xbot/common/wpi_extensions/BaseCommandTest.java
- tests/xbot/common/wpi_extensions/MockSmartDashboardCommandPutter.java
This is ported from the 2015 repo's pull request.
Basically when we wanted to put commands on the smart dashboard (like certain reset/calibration commands that don't need buttons) we have now written code that can't be unit tested since the SmartDashboard static would break.
This add a helper function on commands you can call to set it to the smartdashboard if the code is running on the real robot or not.
@JohnGilb @WasabiFan @shahronak @riverole
> SmartDashboard command putter

- src/xbot/common/properties/ITableProxy.java
- src/xbot/common/properties/PropertyManager.java
- src/xbot/common/properties/SmartDashboardTableWrapper.java
- src/xbot/common/properties/TableProxy.java
- tests/xbot/common/properties/PermanentStorageProxyTest.java
@aschokking @WasabiFan @riverole @shahronak 
This is something I saw happen a few times last year - where we would remove a property from the code, but then it would continue to get loaded/saved indefinitely until I deleted it manually from the flat file.
> Clear the permanent store before saving properties

- src/xbot/common/injection/RobotModule.java
- src/xbot/common/properties/DatabaseStorageBase.java
- src/xbot/common/properties/PermanentStorage.java
- src/xbot/common/properties/Property.java
- src/xbot/common/properties/PropertyManager.java
- tests/xbot/common/injection/BaseWPITest.java
- tests/xbot/common/injection/UnitTestModule.java
- tests/xbot/common/properties/MockPermamentStorage.java
- tests/xbot/common/properties/PermanentStorageProxyTest.java
- tests/xbot/common/properties/PropertyTest.java
Add a level of abstraction infront of the database. Only use the real database for those tests but use in memory table for everything else.
@JohnGilb @WasabiFan
> Stop using database for most unit tests

- DeployJRE/build.xml
- DeployJRE/readme.txt
The official name of the file includes the `.tar` in the extension, as it should since we are `untar`-ing it (i.e. it is a tarball that has been gzipped).
> Use correct file name in DeployJRE project

- src/xbot/common/controls/actuators/MockCANTalon.java
Fixed a bug where getPosition was returning encoder ticks what was set in setPosition
> Fixed a bug where getPosition was returning encoder ticks

- src/xbot/common/command/BaseRobot.java
- src/xbot/common/command/BaseSubsystem.java
- src/xbot/common/command/TelemetrySource.java
* Add an optional `updateTelemetry` method on BaseSubsystem
* Add ability for these subsystems to be registered with BaseRobot class and they will be called automatically during every periodic loop.
The goal here was to make it as low overhead as possible, subsystems just need to override the method and then get registered (so no need for additional boilerplate commands to call updateTelemetry).
> updateTelemetry on BaseSubsystem

- src/xbot/common/injection/RobotModule.java
- src/xbot/common/math/PIDManager.java
- src/xbot/common/math/PIDManagerFactory.java
- src/xbot/common/math/XYPairManager.java
- tests/xbot/common/injection/UnitTestModule.java
- tests/xbot/common/math/PIDManagerTest.java
Make it easier to create a PIDManager with a factory implemented using guice's AssistedInjection.
Updated the PIDManagerTest with how to use it.
This has the advantage of not requiring consumers to provide all of the injectable dependencies PIDManager has now or in the future. Also general good practice in how AssistedInjection works to help us see if there are other places we might want to leverage it.
> Guice-up PIDManager creation

- src/xbot/common/properties/BooleanProperty.java
- src/xbot/common/properties/DoubleProperty.java
- src/xbot/common/properties/Property.java
- src/xbot/common/properties/StringProperty.java
There's a missing check in the property classes which opens us up to fatal errors (to the extent of "Robots don't quit!") when the underlying data store is missing the property's key. This PR fixes that issue and replaces the `NullPointerException` with an angry error print.
Note that I decided to make the `StringProperty` match the others even though it isn't strictly necessary; it seems better to return the default value instead of `null`.
> Prevent error when property's key is missing from the store

- src/xbot/common/injection/RobotModule.java
- src/xbot/common/properties/PreferenceStorage.java
Instead of using the Derby database, we use the Preferences system, which has a simple way of serializing things to disk on the robot.
> Use WPILib's Preferences system to store Properties

- .gitignore
There is an FRC plugin that has all the necessary libraries for people to use intelliJ
> Possibly allow people to use intelliJ for programming

- src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
- src/main/java/xbot/common/subsystems/drive/control_logic/HeadingAssistModule.java
- src/main/java/xbot/common/subsystems/drive/control_logic/HeadingModule.java
- src/test/java/xbot/common/subsystems/drive/HeadingAssistModuleTest.java
I've been doing some research into how other teams add automation to the drivetrain, and in a couple places I saw a pattern of using a gyro to automatically add "turning resistance" to the robot, so that when the driver stops rotating, the robot stops turning much faster.
The basic mechanism is to use a D-only PID on the gyro.
I've added this as a variant into our HeadingAssistModule - now we can choose between "hold an orientation after rotating" and "rapidly slow down after rotating"
> Adds a velocity-decay version of the HeadingAssistModule

- src/main/java/xbot/common/controls/actuators/XCANTalon.java
When the class was updated to the new API the "mode" property wasn't fully removed, causing telemetry to never be updated because it checked whether that property was initialized.
> Fix CAN talon telemetry

- src/main/java/xbot/common/subsystems/drive/ConfigurablePurePursuitCommand.java
- src/main/java/xbot/common/subsystems/drive/PurePursuitCommand.java
- src/test/java/xbot/common/subsystems/drive/PurePursuitCommandTest.java
Existing usages of `PurePursuitCommand` will now instead use `ConfigurablePurePursuitCommand` (will open a PR in 2018 repo). Now the `PurePursuitCommand` is an abstract class which we can subclass for individual uses.
> Restructure PurePursuitCommand to allow custom implementations

- src/main/java/xbot/common/controls/sensors/XFTCGamepad.java
- src/main/java/xbot/common/controls/sensors/XJoystick.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockFTCGamepad.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockJoystick.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/FTCGamepadWpiAdapter.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/JoystickWPIAdapter.java
This is intended to allow rumbling of devices we use as plain joysticks but know in reality are rumble-able controllers. This is pretty much a hack. For the alternative (which I want to look at _after_ competition as it makes some code cleaner), see https://github.com/Team488/SeriouslyCommonLib/tree/xbox-controller-rumble-dpad and https://github.com/Team488/TeamXbot2018/tree/adopt-xbox-controller-class. The primary issue here is that the Xbox controller class's inheritance tree is entirely separate from our other HIDs.
> Allow accessing internal HID in joystick objects

- src/main/java/xbot/common/injection/SeriouslyCommonLibTestModule.java
- src/main/java/xbot/common/subsystems/drive/PurePursuitCommand.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
- src/main/java/xbot/common/subsystems/pose/MockBasePoseSubsystem.java
- src/test/java/xbot/common/subsystems/drive/PurePursuitCommandTest.java
- src/test/java/xbot/common/subsystems/pose/BasePoseTest.java
- src/test/java/xbot/common/subsystems/pose/PoseSubsystemTest.java
there could be rotational thrashing as the robot was settling on a point and was alternating between tracking a rabbit ahead/behind of it.
> Fixed a bug in PurePursuitCommand around forward/reverse modes 

- lib/log4jConfig/log4j.xml
- src/main/java/xbot/common/command/BaseRobot.java
- src/main/java/xbot/common/logging/OneLogFilePerRunRollingFileAppender.java
This aims to fix a few problems:
- It's hard to find where an individual session started
- It's hard to understand what the robot's overall match state was at a given time
- Searching for a particular match is almost impossible
There are two primary changes here:
- The log file is "rolled over" every time the code loads. The most recent load will be called `default.log`, the previous will be `default.log.1`, then `default.log.2` and so on. We now allow 50 log files to be stored, each up to 0.5MB. In total, this allows us to store _less history_ than we did before, in the typical case; I'm worried that increasing the file count too high will have a performance impact because it must rename every existing file whenever the code starts.
- Each log line now includes some match context after …
> Better logging

- src/main/java/xbot/common/subsystems/drive/control_logic/HeadingModule.java
- src/test/java/xbot/common/subsystems/drive/HeadingModuleTest.java
For the longest time, this module has normalized error from a -1 to 1 scale, which has made tuning PID challenging. Now that it's in degrees, setting an error threshold of 5 will mean 5 degrees.
> Heading Module uses Degrees instead of normalized error

- src/main/java/xbot/common/math/ContiguousHeading.java
- src/main/java/xbot/common/math/PlanarTestVisualizer.java
- src/main/java/xbot/common/math/PlanarVisualizationPanel.java
- src/main/java/xbot/common/math/PurePursuitTest.java
- src/main/java/xbot/common/math/XYPair.java
- src/main/java/xbot/common/subsystems/drive/PurePursuitCommand.java
- src/test/java/xbot/common/math/XYPairTest.java
- src/test/java/xbot/common/subsystems/drive/PurePursuitCommandTest.java
The Pure Pursuit command now has another (potentially more efficient) way of navigating the field. Before, due to the motion budget, it had to finish most of its rotation before it began translating.
Now, it translates proportional to the dot product of the robot's vector and the vector to the rabbit. This means that if the rabbit is behind it, it will back up while turning, at 90 degrees it will not translate, and then it will start driving forward as it finishes the turn.
> Pure Pursuit can make 3-point turns

- src/main/java/xbot/common/command/BaseCommandGroup.java
- src/main/java/xbot/common/command/SimpleCommandGroup.java
- src/test/java/xbot/common/command/SimpleCommandGroupTest.java
For the scenario of needing to create a quick simple command group to for instance run 2 things in parallel, this class will allow doing so without having to create a new class each time.
For example:
```java
SimpleCommandGroup manualBothLegs = new SimpleCommandGroup("manualBothLegs", Arrays.asList(manualFrontCommand, manualRearCommand), ExecutationType.Parallel);
```
> SimpleCommandGroup

- azure-pipelines.yml
- build.gradle
So people don't have to remember to run the report task afterwards all the time, doesn't seem to talk even a second to generate and that way it'll support viewing it in the gui.
> Always run coverage report

- .vscode/extensions.json
- .vscode/settings.json
VScode settings to display code coverage inline using the Coverage Gutters extension (seems to be the most popular coverage extension at this time).
> Add settings to use coverage gutters in vscode

- src/main/java/edu/wpi/first/wpilibj/MockSolenoid.java
- src/main/java/xbot/common/controls/actuators/XSolenoid.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/SolenoidWPIAdapter.java
- src/main/java/xbot/common/injection/wpi_factories/DevicePolice.java
- src/test/java/xbot/common/injection/wpi_factories/TestDevicePolice.java
* Added capability to DevicePolice to check channel numbers against a minimum and maximum allowed channel value
* Set WPI solenoid adapter to allow channels from 0-7
* Unit tests for DevicePolice
> Prevent solenoids from being created with an invalid channel

- src/main/java/xbot/common/command/NamedInstantCommand.java
- src/main/java/xbot/common/controls/sensors/AdvancedXboxButton.java
- src/main/java/xbot/common/controls/sensors/XXboxController.java
For later dumping of what the mapping is (https://github.com/Team488/TeamXbot2020/pull/89).
Notably changes how getifAvailable works so that it doesn't use the super class at all but instead keeps track itself of how buttons work. This also means this won't work for any other kind of gamepad but that should be okay for this season.
> XXboxController: Track which command is mapped to which button

- build.gradle
- src/main/java/xbot/common/controls/sensors/XEncoder.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockEncoder.java
- src/main/java/xbot/common/injection/wpi_factories/DevicePolice.java
- src/main/java/xbot/common/simulation/ISimulatableSensor.java
- src/main/java/xbot/common/simulation/IWebotsSensor.java
- src/main/java/xbot/common/simulation/SimulationPayloadDistributor.java
- src/test/java/xbot/common/simulation/SimulationPayloadDistributorTest.java
Basic idea:
Both sides refer to sensors using their DevicePolice IDs, which are a combination of the kind of port they use (e.g. USB, DigitalIO, CAN, etc..) and the number of the port. The server packages this up into a JSON array of sensors.
The payload is read by a client somewhere, then handed off to the SimulationPayloadDistributor. This reads each sensor entry, gets the full ID, and retrieves the base object.
Each mock sensor will now implement IWebotsSensor (name suggestions welcome), which has one method: `public void  ingestSimulationData(JSONObject payload);` Each actual device will know how to read their specific payload.
Encoders might only need one value - the # of ticks. Our IMU might need a dozen.
> Smarter Device Police & SimulationPayloadDistributor

- src/main/java/edu/wpi/first/wpilibj/MockXboxControllerAdapter.java
- src/main/java/xbot/common/controls/sensors/XXboxController.java
- src/main/java/xbot/common/simulation/ResetSimulatorPositionCommand.java
So test code doesn't have to know if the gamepad is inverted or not. This was messing up the curriculum.
> Mock Gamepad: apply inversions on set

- src/main/java/edu/wpi/first/wpilibj/MockSolenoid.java
- src/main/java/xbot/common/command/BaseRobot.java
- src/main/java/xbot/common/simulation/ISimulatableSolenoid.java
- src/test/java/xbot/common/simulation/SimulatedSolenoidTest.java
We added to webots the ability to control solenoid like motors on the simulated robot by setting them on/off and they'll PID by position to their max or min position.
https://github.com/Team488/Webots/pull/70
This PR adds support in SCL to send those simulated motor values based on solenoid being on or off.
> Add basic support for simulating solenoids

- .vscode/extensions.json
- src/main/java/xbot/common/injection/RobotModule.java
- src/main/java/xbot/common/injection/SimulatorModule.java
- src/main/java/xbot/common/injection/UnitTestModule.java
- src/main/java/xbot/common/properties/BooleanProperty.java
- src/main/java/xbot/common/properties/DoubleProperty.java
- src/main/java/xbot/common/properties/Property.java
- src/main/java/xbot/common/properties/PropertyFactory.java
- src/main/java/xbot/common/properties/StringProperty.java
- src/main/java/xbot/common/properties/XPropertyManager.java
Allow marking some properties as `Debug`, they'll only ever use inMemory for their random access store.
We could make this more complicated with more levels doing more things later but this is a good start.
There's no unit testing on any of this code right now.
> Property system: Add property level capability

- src/main/java/xbot/common/controls/sensors/XCANCoder.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockCANCoder.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/CANCoderAdapter.java
- src/main/java/xbot/common/injection/RobotModule.java
- src/main/java/xbot/common/injection/SimulatorModule.java
- src/main/java/xbot/common/injection/UnitTestModule.java
- src/main/java/xbot/common/injection/wpi_factories/CommonLibFactory.java
- src/test/java/xbot/common/injection/wpi_factories/TestCommonLibFactory.java
I've added a new XCANCoder here to keep XAbsoluteEncoder from being tightly coupled to CANCoder.
> Feature/Add ability to get faults and set status frames on CANCoder

- .gitignore
- .vscode/settings.json
- build.gradle
When VS Code builds java code for intellisense / running tests / debugging, it doesn't use Gradle directly. The VS Code java language plugin internally uses Eclipse's Java build tools to try to run a gradle project.
Essentially this change tells the Gradle build to generate eclipse files (.classpath, .factorypath, etc) when run directly, and the VS Code-triggered build (for tests or debugging) can also consume the plugin outputs. The VS Code Java language server also uses this classpath to search for source files (for intellisense). The additional plugins let the Eclipse-driven build also run dagger code generation, which means that intellisense should just work.
Classpath and factorypath are generated at build and not checked in.
> Fix generation of Dagger outputs for non-gradle builds

- src/main/java/xbot/common/subsystems/drive/PurePursuitCommand.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
- src/test/java/xbot/common/subsystems/drive/PurePursuitCommandTest.java
- src/test/java/xbot/common/subsystems/pose/PoseSubsystemTest.java
- src/test/java/xbot/common/subsystems/pose/commands/ResetDistanceCommandTest.java
Use FRC Coordinate System (x is "down the field", y is "across the driver station").
The most significant change for us is that 0 degrees is the default, and that robot-oriented driving forward is +X motion
> Use FRC Coordinate System

- src/main/java/xbot/common/command/BaseMaintainerCommand.java
- src/main/java/xbot/common/command/BaseRobot.java
- src/main/java/xbot/common/command/BaseSetpointSubsystem.java
- src/main/java/xbot/common/controls/sensors/XDutyCycleEncoder.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockDutyCycleEncoder.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/DutyCycleEncoderWpiAdapter.java
- src/main/java/xbot/common/injection/components/BaseComponent.java
- src/main/java/xbot/common/injection/modules/MockDevicesModule.java
- src/main/java/xbot/common/injection/modules/RealDevicesModule.java
- src/test/java/xbot/common/command/MockSetpointSubsystem.java
- src/test/java/xbot/common/controls/sensors/DutyCycleEncoderTest.java
- Modify the Maintainer/Setpoint classes to be generics
- Add DutyCycleEncoder (since we have some through-bore encoders that will need this for absolute positioning)
> Generic Maintainer System and DutyCycleEncoder

- src/main/java/xbot/common/properties/PropertyFactory.java
this will allow us to remove properties from the network tables at the factory level, instead of just per property (what we can do today).
> Allow setting a default property level per factory

- src/main/java/xbot/common/command/BaseMaintainerCommand.java
Auto is a bit special in that as soon as it starts, we tend to also start a huge CommandGroup that requires nearly everything. However, any maintainers that initialize will cancel any command requiring their setpoint, which will stop the entire autonomous command.
This small check prevents that from happening.
> Maintainers don't cancel setpoint commands in Autonomous

- src/main/java/xbot/common/properties/BooleanProperty.java
- src/main/java/xbot/common/properties/DoubleProperty.java
- src/main/java/xbot/common/properties/StringProperty.java
- src/main/java/xbot/common/properties/XPropertyManager.java
- src/test/java/xbot/common/properties/PropertyTest.java
This was introduced a couple of years ago, and after several competitions where the robot lost its properties, this behavior is suspected to be the culprit. Running a different robot program on the same RoboRIO would clear the persistent storage.
> Remove the PermanentStorage cleanup behavior

- src/main/java/xbot/common/command/BaseRobot.java
- src/main/java/xbot/common/controls/io_inputs/XPhotonCameraInputs.java
- src/main/java/xbot/common/controls/sensors/XCANCoder.java
- src/main/java/xbot/common/controls/sensors/XPhotonCamera.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockCANCoder.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockPhotonCamera.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/CANCoderAdapter.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/PhotonCameraAdapter.java
- src/main/java/xbot/common/injection/modules/MockDevicesModule.java
- src/main/java/xbot/common/injection/modules/RealDevicesModule.java
- src/main/java/xbot/common/math/XYPair.java
- src/main/java/xbot/common/math/XYPairStruct.java
- src/main/java/xbot/common/vision/XbotPhotonCameraFork.java
- src/main/java/xbot/common/vision/XbotPhotonPoseEstimatorFork.java
- vendordeps/photonlib.json
* Use some more modern AKIT conventions (stop Logger instance, use the new "/U/Logs" call to automatically write to a USB drive)
* Make XYPair serializable for AKIT
* Update PhotonVision
* Start writing code for an AKIT-ready camera (PV needs to release v2024.1.5+ so objects can be serialized for Akit)
* Update CANCoder to Phoenix6 so we can use the "auto-zero" button in Phoenix Tuner X
> Move some vision to SCL, improve AdvantageKit Integration

- src/main/java/xbot/common/properties/BooleanProperty.java
- src/main/java/xbot/common/properties/DoubleProperty.java
- src/main/java/xbot/common/properties/StringProperty.java
Bug introduced when default properties were persisted to storage again.
Only log if value is non-default.
Removed unboxing, java does auto-unboxing.
> Fix logging when property values are non-default

- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDefaultCommandMap.java
This is code common to all swerve bots.
Move swerve injectors to common lib from robot code.
> Move the swerve default command map to SCL

- src/main/java/org/photonvision/PhotonCameraExtended.java
We disabled version checking in a previous commit to avoid a guaranteed crash when the PhotonLib version doesn't match the PhotonLib coprocessor version; but that also exposes us to extra risk that some other crash will happen inside the library. Instead, we will just do a quick check to see if there is a version mismatch, and if so choose not to call any PhotonVision functions.
Adds a safe version check and uses that check to disable one or more cameras.
> Add new version checking that won't crash the robot

- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANTalon.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANVictorSPX.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonWPIAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANVictorSPXWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/VictorAppearingAsTalonWPIAdapter.java
Warnings during build show up as red text and are confusing to students.
Deprecation warnings are silenced.
> Silence warnings about deprecated CANCoder class

- src/main/java/xbot/common/command/BaseMaintainerCommand.java
- src/main/java/xbot/common/command/BaseRobot.java
- src/main/java/xbot/common/controls/actuators/XCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/XCANTalon.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockAbsoluteEncoder.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockCANCoder.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/CANCoderAdapter.java
- src/main/java/xbot/common/logic/WatchdogTimer.java
- src/main/java/xbot/common/math/PIDManager.java
- src/main/java/xbot/common/properties/BooleanProperty.java
- src/main/java/xbot/common/properties/DoubleProperty.java
- src/main/java/xbot/common/properties/PreferenceStorage.java
- src/main/java/xbot/common/properties/Property.java
- src/main/java/xbot/common/properties/PropertyFactory.java
- src/main/java/xbot/common/properties/StringProperty.java
- src/main/java/xbot/common/properties/XPropertyManager.java
- src/main/java/xbot/common/properties/package-info.java
- src/main/java/xbot/common/simulation/ExampleSensorData.json
- src/main/java/xbot/common/simulation/WebotsClient.java
- src/main/java/xbot/common/subsystems/BaseXCANTalonSpeedControlledSubsystem.java
- src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java
- src/main/java/xbot/common/subsystems/compressor/CompressorSubsystem.java
- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
- src/test/java/xbot/common/controls/actuators/MockCANTalonTest.java
- src/test/java/xbot/common/injection/BaseCommonLibTest.java
- src/test/java/xbot/common/properties/PropertyFactoryTest.java
- src/test/java/xbot/common/properties/PropertyTest.java
- src/test/java/xbot/common/subsystems/compressor/CompressorSubsystemTest.java
* We should add configuration properties to AKIT, so it can 100% replay the match from the logged data. However, this would cause them to show up in 3 places - Preferences, SmartDashboard, and AKIT. That's a little excessive
* The Preferences system already handles using a network table for random access, so our save/load mechanism was no longer relevant - it can be retired.
* Ephemeral properties are gone - replaced by calls to the AKIT logger.
* Double/String/BooleanProperties now log and hydrate from AKIT like other systems
* The PropertyManager refreshes all properties at the top of each cycle.
> Properties now logged by AKIT

- src/main/java/xbot/common/controls/actuators/XCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/sensors/XSparkAbsoluteEncoder.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockSparkAbsoluteEncoder.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/SparkAbsoluteEncoderAdapter.java
Current plans for the robot involve attaching a through-bore encoder to the Arm assembly, and plugging that directly into a nearby SparkMax rather than the RIO.
XCANSparkMax objects can be asked for a XSparkAbsoluteEncoder object, which in turn must be refreshed like any other base sensor.
I put this together to unblock a student working in the area, but there's probably some way to either join this closer to the existing XAbsoluteEncoder or more strongly separate them.
> Support absolute encoders attached to SparkMax objects

- src/main/java/edu/wpi/first/wpilibj/MockDigitalInput.java
- src/main/java/xbot/common/controls/io_inputs/XDigitalInputs.java
- src/main/java/xbot/common/controls/sensors/XDigitalInput.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/DigitalInputWPIAdapter.java
- src/test/java/xbot/common/injection/factories/TestAllFactoryClasses.java
DigitalInput was not in the AdvantageKit system, so its inputs wouldn't be automatically logged.
DigitalInput now will log values to disc or reload them during replay.
> Add DigitalInput to suite of Akit devices

- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
Swerve steering wasn't rotating the wheels
Call `periodic()` on the motor controller to send the PID values
> Fix missing swerve periodic

- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANSparkMax.java
To allow tests regarding limit switches being pressed
Added limit switch states
> Added limit switch states to MockCANSparkMax

- src/main/java/xbot/common/advantage/AKitLogger.java
- src/main/java/xbot/common/command/BaseCommand.java
- src/main/java/xbot/common/command/BaseMaintainerCommand.java
- src/main/java/xbot/common/command/BaseSubsystem.java
- src/main/java/xbot/common/math/PIDManager.java
- src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java
- src/main/java/xbot/common/subsystems/compressor/CompressorSubsystem.java
- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/SwerveSimpleTrajectoryCommand.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
- src/main/java/xbot/common/trajectory/SimpleTimeInterpolator.java
- src/main/java/xbot/common/trajectory/SwerveSimpleTrajectoryLogic.java
We're using advantage kit more and more to do what we used to use ephemeral property logging. The new syntax is a little verbose though with us having to do prefix setting ourselves.
Adds a new logger class that wraps akit and does our prefixing.
```diff
-        Logger.getInstance().recordOutput(this.getPrefix() + "ErrorWithinTotalTolerance", withinErrorTolerance);
-        Logger.getInstance().recordOutput(this.getPrefix() + "ErrorIsTimeStable", isStable);
+        aKitLog.record("ErrorWithinTotalTolerance", withinErrorTolerance);
+        aKitLog.record("ErrorIsTimeStable", isStable);
```
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206445513269033
> AKitLogger

- src/main/java/xbot/common/subsystems/drive/SwerveSimpleTrajectoryCommand.java
- src/main/java/xbot/common/trajectory/LowResField.java
- src/main/java/xbot/common/trajectory/SimpleTimeInterpolator.java
- src/main/java/xbot/common/trajectory/SwerveSimpleTrajectoryLogic.java
- src/main/java/xbot/common/trajectory/XbotSwervePoint.java
The auto drive code was very unpredictable when on Red Alliance
The pathfinding code no longer flips most points by default; it will need to be specifically instructed to go to coordinates on the red side of the field.
> Don't always flip points

- src/main/java/xbot/common/command/BaseRobot.java
> Only register AKit USB logger if USB device is detected and writable

- src/main/java/xbot/common/controls/actuators/XCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/io_inputs/XCANSparkMaxInputs.java
This will log the values of the limit switches every robot cycle; necessary if we want to do any sort of log replay in the future. Also implicitly puts their values onto NetworkTables for ease of viewing.
CANSparkMax now has limit switch values as part of the "inputs" object for AKIT.
> Add limit switches to the AKIT spark max

- src/main/java/edu/wpi/first/wpilibj/MockDigitalInput.java
- src/main/java/xbot/common/command/BaseMaintainerCommand.java
- src/main/java/xbot/common/controls/sensors/XDigitalInput.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/DigitalInputWPIAdapter.java
- src/main/java/xbot/common/properties/BooleanProperty.java
- src/main/java/xbot/common/properties/DoubleProperty.java
- src/main/java/xbot/common/properties/StringProperty.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
- src/test/java/xbot/common/injection/factories/TestAllFactoryClasses.java
- Fixes for digital inputs not having parents
- Comment out useless spew when properties not found (speeds up robot boot)
- Add "important" tag to maintainer properties around stability
> Fix Digital Input AKIT names and mark Maintainer properties important

- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
We are using the Swerve Drive motor controllers for an absolute encorder for another mechanism.  The absolute encoder pinout conflicts with the limit switchces that are enabled by default, causing swerve drive problems.
Disable limit switches on all swerve motor controllers
> Disable limit switches on motor controllers for swerve drives

- src/main/java/xbot/common/controls/actuators/XCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANSparkMax.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
Since I'm touching Spark Max classes, I'm also cleaning up warnings, and undoing a breaking change to XCANSparkMaxFactory
https://app.asana.com/0/38541457243752/1206617786624122/f
* Set default current to 40A on all SparkMax instances
* Restore a create() overload on XCANSparkMaxFactory
* Clean up IDE warnings
> Set the default current for Spark Max motor controllers to 40A.

- src/main/java/xbot/common/command/BaseCommand.java
- src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java
We have more and more commands with `execute` being a no-op. At this point it no longer seems to have a pedagogical reason to be enforced on every command.
- `execute` no longer mandatory on all commands.
- Convenience function on AutonomousSelector for updating a dashboard property.
> Autonomous messaging and make execute() not abstract.

- vendordeps/photonlib.json
Orange Pi is running newer photonvision
> Bump photonlib to 2.6 to match Orange Pis

- src/main/java/xbot/common/controls/sensors/XDigitalInput.java
- src/test/java/xbot/common/controls/sensors/DigitalInputTest.java
It's nice to set up inversion via electrical contracts rather than after creating the object.
XDigitalInput now respects the inversion parameter of the DeviceInfo when being created.
> XDigitalInput supports inversion at creation time

- src/main/java/xbot/common/logic/TimeStableValidator.java
Useful in scenarios where the validator is "fed" once per robot cycle, but wants to be read multiple times. The value could be cached in the calling class, but this is convenient.
Adds `peekStable()` alongside the existing `checkStable(boolean value)`, returning the last value of the latter.
> TimeStableValidator now allows you to "peek" on the result

- src/main/java/xbot/common/advantage/AKitLogger.java
We're starting to have too many values being sent to akit. This should allow us to mark some as debug and not send them during competitions at least.
https://app.asana.com/0/38541457243752/1206617786624119
- new static log level on AKitLogger that would be set to INFO during competitions (statically, maybe in Robot.java?) and otherwise DEBUG
- individual loggers can be set into debug or info mode before calling to log. If the global level is info but the local level is debug, the call to log will no-op
> Add log level concept to AKitLogger

- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
Motor PIDs have been working well for us.
Change drive motors to use onboard pids by default
> Swerve uses motor pid by default

- src/main/java/xbot/common/injection/electrical_contract/XCameraElectricalContract.java
Didn't even realize this was an SCL file - will evaluate a cleaner way to do this when we have multiple "kinds" of cameras.
Need some way to separate note cameras from apriltag cameras.
> Support multiple kinds of cameras in Electrical Contract

- src/main/java/xbot/common/command/BaseSetpointSubsystem.java
This should make it easier to make SetTargetCommands for a BaseSetpointSubsystem, including with a specific value
Very simple methods, not tested
> Add factory helpers for making SetTargetCommands

- src/main/java/xbot/common/trajectory/LowResField.java
- src/main/java/xbot/common/trajectory/Obstacle.java
In cases where obstacles were just slightly misaligned with each other, the existing "greedy" algorithm to find the shortest route would sometimes invalidate too many options, leading to some really ugly drive patterns. This allows the route planner to return any corners it used when deciding between two options.
When handling the "Handling mixed case - two parallel lines, one inside" case, after grabbing the two nearest corners to find the one closest to the robot, return the other one back to the obstacle.
> Return corners when we are too greedy.

- src/main/java/org/photonvision/PhotonCameraExtended.java
- src/main/java/xbot/common/controls/actuators/XCANSparkMax.java
- src/main/java/xbot/common/controls/io_inputs/PhotonCameraExtendedInputs.java
- src/main/java/xbot/common/subsystems/vision/AprilTagCamera.java
- src/main/java/xbot/common/subsystems/vision/SimpleCamera.java
* Cameras weren't actually logging their data, so later replays won't be accurate.
* We were noticing pose errors that are related to CAN timeouts, where the library will report 0 (more or less) rotations rather than caching the last value. This causes havoc for positioning.
* Cameras now log their data to disk
* XCANSparkMAX checks for errors, and if it sees them, rolls back to the inputs from a previous frame.
> Akit Compatability for Camera and Telemetry fix for SparkMAX

- src/main/java/xbot/common/trajectory/LowResField.java
- src/main/java/xbot/common/trajectory/ProvidesWaypoints.java
- src/main/java/xbot/common/trajectory/SwerveSimpleTrajectoryLogic.java
- src/test/java/xbot/common/trajectory/LowResFieldTest.java
In preparation for replacing the LowResField for pathfinding, refactoring out the key functions it exposes to consumers as an interface other classes could implement.
* Adds `ProvidesWaypoints` interface; LowResField now implements that interface.
> Important part of LowResField is an interface

- src/main/java/xbot/common/command/BaseRobot.java
Added /etc/fstab entry to mount our usb drive to this location in a stable fashion:
```
LABEL=LOGSDRIVE     /media/logs    vfat   defaults 0 0
```
> Change logs directory to new permanent location

- src/main/java/xbot/common/trajectory/SwerveSimpleTrajectoryLogic.java
Noticed this when messing around with autos in the simulator. Produces a lot of warnings.
If you try to go to where you already are, it just adds a point at where you are with 0.1 seconds so you can "get there" quickly.
> Handle SwerveLogic case where you try to go to where you already are

- src/main/java/org/photonvision/PhotonCameraExtended.java
- src/main/java/xbot/common/controls/io_inputs/PhotonCameraExtendedInputs.java
> Keep track of PhotonResult timestamp and propegate other inputs

- src/main/java/xbot/common/subsystems/drive/control_logic/HeadingModule.java
The HeadingModule can now hold onto a useful heading and keep pointing at it
Adds `freezeHeading()` and `calculateFrozenHeadingPower()` methods to the Heading Module. We were often doing this thing in commands where the command would have a little state machine to do this, but since this repeats, I've put it into the HeadingModule.
> Adding Heading Module helper functions for holding rotation

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/main/java/xbot/common/controls/io_inputs/XCANMotorControllerInputs.java
The XCANMotorController skipped the input processing & `refreshDataFrame()` aspects that get its data recorded by AKIT.
- Adds basic XCANMotorControllerInputs, just handling positions and velocity
- Fixes a bug in the naming scheme for motors - steering and drive were using the same functions
> "AKIT-ify" XCANMotorController

- build.gradle
- src/main/java/xbot/common/injection/modules/SimulationModule.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
- src/main/java/xbot/common/subsystems/pose/MockBasePoseSubsystem.java
- src/main/java/xbot/common/subsystems/pose/SimulatedPositionSupplier.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVision.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVisionSimulated.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionSubsystem.java
This branch is a fork off of the feature/apriltag-vision branch that initially added these april tag vision classes. The next thing we really wanted was the ability to use the simulated april tags so that when driving the robot locally in the simulator we can get back 'tags' the simulated robot sees and test our logic.
Copies in the *Simulated logic from the MapleSim skeleton project. Added Dagger injection goo to allow swapping between these implementations.
Updated wpilib to 2025.2.1 because we need it to get the 2025 april tags for reefscape.
Neither branch has actually been used yet in a robot project so this is all on prospect for now.
I'm still iffy on the dagger side of this, is there a better way of structing things?
Not tested at all, just compiles
> AprilTagVisionSimulated

- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVisionSimulated.java
Allow the simulated cameras to stream what they see, making it easier to debug what's going on.
The cameras stream on the normal photonlib ports (starting at 1181)
> Sim Camera streams

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/actuators/XCANMotorControllerFactoryImpl.java
- src/main/java/xbot/common/controls/actuators/XCANMotorControllerPIDProperties.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/main/java/xbot/common/properties/DoubleProperty.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
- src/test/java/xbot/common/controls/actuators/CANMotorControllerTest.java
- src/test/java/xbot/common/injection/factories/TestAllFactoryClasses.java
- This allows us to rapidly tune PID(F) parameters at runtime for motors.
- Porting logic from XCANSparkMAX to th enewer XCANMotor
> Add PIDProperties to the XCANMotor

- src/main/java/xbot/common/advantage/AKitLogger.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockCANCoder.java
- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
Small bugs found during debugging of 2023 and 2024 swerve drives
- Allows each swerve module to log unique data
- Change the "swerve display" to INFO level
- Change Mock CANCoder to use newer -0.5 to 0.5 range.
> Various swerve control & visualization fixes

- src/main/java/xbot/common/controls/sensors/XXboxController.java
- src/test/java/xbot/common/controls/sensors/XboxControllerTest.java
Ensure nobody can reserve button 1 and then button A without getting a test-time exception.
Reserving an XboxButton also reserves the "basic" button.
> Fix a bug where you could reserve button 1 AND button A on the controller

- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
Fixes Pose2d conversions from Blue Alliance to Red Alliance
BasePoseSubsystem fieldXMidpointInMeters
> Field Length Increased

- src/main/java/org/photonvision/PhotonCameraExtended.java
- src/main/java/xbot/common/command/BaseSubsystem.java
- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/sensors/XAbsoluteEncoder.java
- src/main/java/xbot/common/controls/sensors/XDigitalInput.java
- src/main/java/xbot/common/controls/sensors/XDutyCycleEncoder.java
- src/main/java/xbot/common/controls/sensors/XGyro.java
- src/main/java/xbot/common/controls/sensors/XSparkAbsoluteEncoder.java
It's too easy to forget to setup a refreshDataFrame() call on your subsystem.
Have every Subsystem be DataFrameRefreshable and create a register call that can be used to register devices as we create them so it's harder to forget.
Added the interface to a bunch of devices that already implemented the contract.
> Base subsystem refreshable

- src/main/java/xbot/common/advantage/DataFrameRefreshable.java
- src/main/java/xbot/common/command/BaseSubsystem.java
It's not obvious how DataFrameRefreshable works. Documented the behavior so that we don't need to re-discover in the future.
> Document how DataFrameRefreshable works

- src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
We're moving to MapleSim, so this older approach of getting robot position/translation can be removed.
> Remove simulation shims that allowed old simulators to access drive intents

- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
This would be called by code simulating an internal pid, setting the output of the pid operation without changing the control mode.
> Add setPowerInternal method to MockCANMotorController 

- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
This method is used for the CalibrateDriveCommand. I needed a method to zero the swerve modules.
BaseSwerveDriveSubsystem
> added method setAllSwerveModulesToTargetState

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
We want to be able to run the SysId routines on a swerve steering motor, to see if we can make use of SysId.
Adding the bits necessary for SysId to run.
> Add hooks to be able to run SysId routines on a swerve steering motor

- src/main/java/xbot/common/subsystems/drive/BaseDriveSubsystem.java
We have repeated code throughout the robot that does a bunch of math to ultimately return a power vector in the direction of your target. Centralizing on BaseDriveSubsystem.
> Add drive method: getPowerForRelativePositionChange

- src/main/java/xbot/common/subsystems/drive/SwerveKinematicsCalculator.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
- src/main/java/xbot/common/trajectory/SimpleTimeInterpolator.java
- src/main/java/xbot/common/trajectory/SwerveSimpleTrajectoryLogic.java
There are some old assumptions baked into the BasePoseSubsystem that don't play nice with our modern world of vision-assisted pose updating.
- Create explicit function for only updating from gyro data
- Existing `getCurrentHeading` command can now return data from subclasses (e.g. PoseEstimator data)
- Debug spew reduced for swerve navigation
- Interpolation "ghost" now has orientation
> Navigational Fixes

- src/main/java/xbot/common/logging/Pluralizer.java
- src/main/java/xbot/common/properties/DistanceProperty.java
- src/main/java/xbot/common/properties/PropertyFactory.java
- src/test/java/xbot/common/properties/PropertyFactoryTest.java
As we're using Unit-ed measures more and more, an awkward seam in our current code is our heavy use of DoubleProperties that could be anything. Right now it's up to the property creator to do a good job of saying what the units it'll be interpreted of as (and students almost never do this without prompting).
I've done an example of DistanceProperty here and if this looks good I'll do the other ones we're using heavily like AngleProperty and VelocityProperty which I imagine will cover most of the bases.
NOTE: I tried doing a generic UnitProperty<U extends Unit> but the typing of Unit.of/in is too loose and I couldn't get it working. Unit.of returns Measure<?> for example.
- New DistanceProperty class, bit notable behaviors here are:
- The measure is inferred from the default value (since …
> Unit-based-properties: DistanceProperty proof of concept

- src/main/java/xbot/common/controls/sensors/mock_adapters/MockAbsoluteEncoder.java
allows us to simulate absolute encoders
MockAbsoluteEncoder
> added new method setPosition_internal

- src/main/java/xbot/common/command/BaseRobot.java
- src/main/java/xbot/common/command/XScheduler.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockLaserCAN.java
- src/test/java/xbot/common/command/SetpointSystemTest.java
- src/test/java/xbot/common/command/XSchedulerTest.java
When robot unit tests run the scheduler, it uses a static instance of the CommandScheduler created by WPI Lib. That means that we need to be able to clear stale subsystems out of the scheduler if we want to instantiate another scheduler or we could get unexpected behavior when running multiple tests.
Add the ability to fully clean out the CommandScheduler. BaseRobot will do this on initialize just in case it's being run as part of a test, but on a real robot the scheduler will start empty.
> Add the ability to fully reset the scheduler

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/test/java/xbot/common/controls/actuators/CANMotorControllerTest.java
We don't have a great way to force a motor to stop if a condition is hit. Add a crude implementation that checks a supplier on every robot periodic() loop.
This isn't a perfect solution, we only check every 50ms, which could be more than enough time for the robot to rip itself apart.
> Add crude software-based motor limits

- src/main/java/xbot/common/command/BaseMaintainerCommand.java
- src/main/java/xbot/common/subsystems/pose/BasePoseSubsystem.java
The 2025 field is rotationally symmetric between red and blue. For now, changing the default to rotational symmetry, but preserving functions for mirror symmetry.
Nothing for consumers of SCL.
> Change default blue->red to "rotational symmetry" rather than "mirror symmetry"

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/main/java/xbot/common/controls/sensors/XCANCoder.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/CANCoderAdapter.java
- src/main/java/xbot/common/logging/AlertGroups.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionCameraHelper.java
- vendordeps/REVLib.json
Logging errors on every sensor update is expensive, and it's difficult to get an overview of faults.
Ignore errors when reading status signals on CANCoders and TalonFX, and instead emit an alert when unhealthy.
This doesn't eliminate all of the log spew, just most of it.
> Reduce CANCoder and TalonFX log spew, add Alert signals for health

- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
We were seeing that some set commands might fail, so we should catch and retry failures.
All set commands are now wrapped in a retry function.
Each retry will timeout after 0.1 seconds. Is that a problem?
> Retry all TalonFX set commands

- src/main/java/xbot/common/injection/electrical_contract/XSwerveDriveElectricalContract.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveSubsystem.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveSteeringSubsystem.java
Calibration for our serve modules is wrong, but each robot will need different calibrations.
Expose gear ratios for swerve drive in the contract. Offload the math to the ratio converters in the motor controller classes.
> Set swerve calibrations for X2i, make configurable via contract

- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
In the Phoenix 6 API, when you update a configuration, any unset value will be cleared unless you first do a blocking call to refresh() to read it from the device. This could be easily prone to bugs and accidentally lost configurations.
Cache configuration of TalonFX on startup and always work on the cached object, applying sections of it when necessary.
> Make configuration writing more resilient on TalonFX

- src/main/java/xbot/common/subsystems/drive/swerve/SwerveDriveRotationAdvisor.java
Too many layered deadbands - this allows us to effectively remove one if needed.
> Allow new constructor in SwerveDriveRotationAdvisor that takes in a deadband

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
Lets us set an acceleration limiter on the core drive. Useful for preventing things like a PositionalPID from "leaping off the start".
> Allow for slewing the main drive

- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
Using Kobe's Bezier curves wants to expose this for vision to compute with:
```java
var options = XTableValues.TraversalOptions.newBuilder()
.setMetersPerSecond(this.drive.getMaxTargetSpeedMetersPerSecond())
.setAccelerationMetersPerSecond(this.drive.getMaxAccelerationMetersPerSecondSquared())
```
> Exposing maxAccelerationMps2 for calcuting curve.

- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIO.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVision.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionSubsystem.java
- src/main/java/xbot/common/subsystems/vision/MockAprilTagVisionIO.java
- src/test/java/xbot/common/subsystems/vision/AprilTagVisionSubsystemTest.java
> Add ability to get any tag's target observation

- src/main/java/xbot/common/properties/AngleProperty.java
- src/main/java/xbot/common/properties/DistanceProperty.java
- src/main/java/xbot/common/properties/PropertyFactory.java
- src/test/java/xbot/common/properties/PropertyFactoryTest.java
We have a lot of properties that are Angles, so this will help remove a conversion step. 
Also changing these unit based properties to use mutable units internally so hopefully there's slightly less object churn.
> AngleProperty + mutable DistanceProperty

- src/main/java/xbot/common/controls/sensors/XAbsoluteEncoder.java
- src/main/java/xbot/common/subsystems/drive/swerve/SwerveModuleSubsystem.java
Hit some possible null ref exceptions while writing the mother of all unit tests.
Some safety logic to handle nulls, clean up optional use.
> Fix possible null reference exceptiosn discovered while writing tests

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
We had existing logic that looked for null properties to decide if it should create all the PID properties in NetworkTables. With the current setup we always made them even for motors that didn't care about PID.
Tested in sim
> if pid props aren't provided, use null not an empty set 

- src/main/java/xbot/common/subsystems/drive/BaseSwerveDriveSubsystem.java
The slewing code isn't resilient to scenarios where `move()` isn't being actively called, which happens a lot in autonomous commands. Removing this for now.
> Remove Drive Slewing

- src/main/java/xbot/common/command/BaseCommand.java
- src/main/java/xbot/common/command/BaseParallelCommandGroup.java
- src/main/java/xbot/common/command/BaseParallelDeadlineGroup.java
- src/main/java/xbot/common/command/BaseSequentialCommandGroup.java
Reverts Team488/SeriouslyCommonLib#581
Turns out the Scheduler approach we were hoping could replace this doesn't work for stuff inside command groups (one of the main things we care about), so we still might want this way
> Revert "Revert "Add is running Alerts to BaseCommand and CommandGroups""

- src/main/java/xbot/common/subsystems/autonomous/AutonomousCommandSelector.java
- src/main/java/xbot/common/subsystems/autonomous/SetAutonomousCommand.java
Hopefully reducing auto init time by 40 ms by doing position initializing during auto init, these are just the SCL changes I need for my PR on Xbot2025
> Corresponding SCL changes for reducing autonomous init time

- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/CANCoderAdapter.java
Refreshing status signals from CTRE devices appears to be one of the most time consuming operations on the robot.
Use the BaseStatusSignal.refreshAll() capability to refresh signals, which is documented to be faster than refreshing each signal individually.
Blue line is before change, orange line is after change, measured in robot cycle time MS
> Combine status frame refreshes into single operation

- src/main/java/xbot/common/controls/io_inputs/LaserCANInputs.java
- src/main/java/xbot/common/controls/sensors/XLaserCAN.java
- src/main/java/xbot/common/controls/sensors/mock_adapters/MockLaserCAN.java
- src/main/java/xbot/common/controls/sensors/wpi_adapters/LaserCANWpiAdapter.java
LaserCAN only reports new measurements every few robot cycles. We only want the freshest data, so we need to know how old the data is
Track when measurements change, make that latency accessible to user code.
> Report rough measurement latency from LaserCAN devices

- src/main/java/xbot/common/properties/AngleProperty.java
- src/main/java/xbot/common/properties/DistanceProperty.java
Noticed on the robot that it kept reporting on boot that many of our Distance/Angle Properties had non-default values, even though they actually were the same.
> Unit-ed Property equivalence fix

- src/main/java/xbot/common/command/BaseMaintainerCommand.java
- src/main/java/xbot/common/logic/HumanVsMachineDecider.java
- src/test/java/xbot/common/logic/HumanVsMachineDeciderTest.java
On TeleopInit/AutonomousInit, we initialize a whole bunch of commands all at once, possibly leading to high robot cycle times.
Startup the maintainers in Coast when disabled, to make sure at least those don't need to be constructed.
> Run maintainers in disabled, with Coast action

- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIO.java
- src/main/java/xbot/common/subsystems/vision/AprilTagVisionIOPhotonVision.java
- src/main/java/xbot/common/subsystems/vision/MockAprilTagVisionIO.java
- src/test/java/xbot/common/subsystems/vision/AprilTagVisionSubsystemTest.java
This might be worth getting in before the next competition as it might be a reason that we relied on old data, but just a hypothesis at the moment.
Heads up that I have an auto-formatter that usually cleans up files.
Seeing if this helps avoid issues where we think we might be getting new camera target and pose data, but really we just have an old camera frame.
Two new fields on TargetObservation to keep track of when the camera data was added.
> Adding whether a given target observation should be considered stale

- src/main/java/xbot/common/controls/actuators/XCANMotorController.java
- src/main/java/xbot/common/controls/actuators/mock_adapters/MockCANMotorController.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANSparkMaxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANTalonFxWpiAdapter.java
- src/main/java/xbot/common/controls/actuators/wpi_adapters/CANVictorSPXWpiAdapter.java
Both the TalonFX and SparkMAX provide a way to limit the max velocity of a trapezoidal profile. This might be useful.
Expose additional method to set trapezoidal profile max velocity.
> Add method to set the max velocity for a trapezoidal profile
